basePath: /
definitions:
  main.UserDTO:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
host: localhost:9000
info:
  contact:
    email: marckenneth.lomio@gmail.com
    name: Marc Kenneth Lomio
  description: Go Rest API using Swaggo & SQL SERVER DB
  title: Go Rest API
  version: "1.0"
paths:
  /migration:
    post:
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Migrate tables to the sql server
      tags:
      - migration
  /update/user:
    put:
      parameters:
      - description: update user dto
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/main.UserDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.UserDTO'
      summary: Update User
      tags:
      - users
  /user:
    post:
      parameters:
      - description: create user dto
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/main.UserDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.UserDTO'
      summary: Create User
      tags:
      - users
  /users/getListUser:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: List User
      tags:
      - users
swagger: "2.0"
